### ISSUE TITLE
Get selected item

### ISSUE THREAD

**Issue by ghost** [gridNA/GNAContextMenu#2]
Hi, 

I am new in swift and I am working on a project using this one.
But i encountered an issue, how could i detect the selected element (in order to push a view) ?

I tried a lot of thing but it does not work.
Could you please enlighten me a little here ?
(menuItemWasPressed is not working )
Nice projet by the way !

Best regards,

**Comment by Ahmedshubber** [comment]
@gridNA +1 how do you get selected item. @Nadia-B Did you find a solution or is this still unresolved

**Comment by gridNA** [comment]
hi, delegate method `menuItemActivated(_ menuItem: GNAMenuItem, info: [String: Any]?)` should solve the issue. Please check it out. Inside this method, you are getting `GNAMenuItem` which has id. This way you can determine what should be done afterward.
