### ISSUE TITLE
Icon for "Active Icon" not hidden when changed programmatically

### ISSUE THREAD

**Issue by ankraft** [gridNA/GNAContextMenu#4]
Thanks a lot for the library. I found a small glitch.

When I change the icon for the active state via ```changeActiveIcon()``` then that icon is shown on top (!) of the normal icon when I open the menu. I guess there is call to hide that icon missing, such as : 

    @objc public func changeActiveIcon(withIcon icon: UIImage) {
        activeMenuIcon?.removeFromSuperview()
        activeMenuIcon = createMenuIcon(withImage: icon)
		activeMenuIcon?.isHidden = true  // <-- this now hides the active icon initially
    }

**Comment by gridNA** [comment]
@ankraft thanks, good catch
